apiVersion: v1
kind: BuildConfig
metadata:
  name: angular-demo-app-chained-s2i
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  creationTimestamp: '2018-01-08T20:54:22Z'
  name: angular-demo-app-chained-s2i
  namespace: myproject
  resourceVersion: '45008'
  selfLink: >-
    /apis/build.openshift.io/v1/namespaces/myproject/buildconfigs/angular-demo-app-chained-s2i
  uid: 1a6150a7-f4b6-11e7-a959-525400d2f593
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'angular-demo-app-nginx:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: |-
      FROM nginx:1.13.3-alpine
      ## Copy our nginx config
      COPY nginx/ /etc/nginx/conf.d/
      ## Remove default nginx website
      RUN rm -rf /usr/share/nginx/html/*

      ## copy over the artifacts in dist folder to default nginx public folder
      COPY dist/ /usr/share/nginx/html

      EXPOSE 8080

      COPY --chown=1001:0 . /opt/app-root/src
     
      CMD ["nginx", "-g", "daemon off;"]
    images:
      - from:
          kind: ImageStreamTag
          name: 'angular-demo-app-s2i:latest'
        paths:
          - destinationDir: .
            sourcePath: /opt/app-root/src/dist
          - destinationDir: .
            sourcePath: /opt/app-root/src/nginx
    type: Dockerfile
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: 'nginx:1.13.3-alpine'
    type: Docker
  triggers: []
status:
  lastVersion: 6
